server:
  port: 9000

spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/prueba_iuvity
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    database: POSTGRESQL
    show-sql : true
    hibernate:
      ddl-auto: update

  app:
    jwt-secret: JWTSecretKey
    jwt-expiration-milliseconds: 86400000